namespace Hanoi {

    // 在此处添加您的代码
    controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
        pause(speed)
        setCurrentDisk(pointPosition)
        currentDisk.setPosition(光标.x, 光标.y + 16)
    })
    export function createDisk(count: number) {
        color = 1
        length = 32
        DiskY = 100
        for (let index = 0; index < count; index++) {
            picture = image.create(length, 8)
            picture.drawRect(0, 0, length, 8, color)
            color += 1
            picture.fillRect(1, 1, length - 2, 6, color)
            color += 1
            圆盘 = sprites.create(picture, SpriteKind.disk)
            圆盘.setPosition(40, DiskY)
            length += -4
            DiskY += -10
            sprites.changeDataNumberBy(圆盘, "length", length)
            list1.push(圆盘)
        }
    }
    controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
        if (isgamestart) {
            pause(speed)
            if (putDownDisk(currentDisk, pointPosition) ) {

                let x = 40 + pointPosition * 3 * 16;
                let y = 100 - (columns[pointPosition].length - 1 ) * 10
                currentDisk.setPosition(x, y)
                currentDisk = null

                info.changeScoreBy(1)
            } else {
                scene.cameraShake(6, 500)
            }
        }
    })  
    controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
        pointPosition += 1
        pointPosition = pointPosition % 3
        setPosition()
    })
    controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
        Hanoi.transforDiskTo(Hanoi.pillars.num1, Hanoi.pillars.num3)
    })
    export function setPosition() {
        pause(speed)
        if (pointPosition == 0) {
            光标.setPosition(40, 20)
        } else if (pointPosition == 1) {
            光标.setPosition(40 + 16 * 3, 20)
        } else {
            光标.setPosition(40 + 16 * 6, 20)
        }
        if (currentDisk) {
            currentDisk.setPosition(光标.x, 光标.y + 16)
        }
    }
    
    controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
        pointPosition += -1
        pointPosition = (pointPosition + 3) % 3
        setPosition()
    })
    
    let speed = 0
    let 圆盘: Sprite = null
    let picture: Image = null
    let DiskY = 0
    let length = 0
    let color = 0
    export let list1: Sprite[] = []
    export let list2: Sprite[] = []
    export let list3: Sprite[] = []
    let columns = [list1, list2, list3]
    
    let 柱子: Sprite = null
    export let isgamestart = 0
    let pointPosition = 0
    export let 光标: Sprite = null
    
    let distance = 2
    光标 = sprites.create(img`
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        1 1 1 . . . 1 1 1 . . . 1 1 1 
        1 1 1 1 . . 1 1 1 . . 1 1 1 1 
        1 1 1 1 1 . 1 1 1 . 1 1 1 1 1 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
        . . 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . . . 1 1 1 1 1 1 . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 1 . . . . . . 
        `, SpriteKind.pointer)
    export function init() {
        tiles.setCurrentTilemap(tilemap`级别1`)
        scene.centerCameraAt(88, 0)
        setPosition()
        for (let index = 0; index < 3; index++) {
            柱子 = sprites.create(img`
            ......dddd......
            ......dddd......
            ......dddd......
            ......dddd......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            ......bbbb......
            cccccccccccccccc
            cccccccccccccccc
            cccccccccccccccc
            `, SpriteKind.column)
            tiles.placeOnTile(柱子, tiles.getTileLocation(distance, 4))
            distance += 3
            柱子.y += 6
        }
    }

}